src/main/java/edu/iit/sat/itmd4515/sfuseini/web/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.sfuseini.web;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotNull;

/**
 *
 * @author shameemahfuseini-codjoe
 */
@Named
@RequestScoped
public class LoginController extends BaseController {

    private static final Logger LOG = Logger.getLogger(LoginController.class.getName());
    
    @NotNull(message="Username cannot blank")
    private String username;
    @NotNull(message="Password cannot be blank")
    private String password;

    /**
     *
     */
    public LoginController() {
    }

    /**
     *
     * @return
     */
    public String getRemoteUser() {
        return context.getExternalContext().getRemoteUser();
    }

    /**
     *
     * @return
     */
    public boolean isManager() {
        return context.getExternalContext().isUserInRole("MGR_ROLE");
    }

    /**
     *
     * @return
     */
    public boolean isLaborer() {
        return context.getExternalContext().isUserInRole("LBR_ROLE");
    }

    /**
     *
     * @return
     */
    public boolean isClerk() {
        return context.getExternalContext().isUserInRole("CLRK_ROLE");
    }

    /**
     *
     * @return
     */
    public String doLogin() {
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
            request.login(username, password);
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Incorrect username or password", "Invalid username or password"));
            return "/login.xhtml";
        }
        return "/welcome.xhtml?faces-redirect=true";
    }

    /**
     *
     * @return
     */
    public String doLogout() {
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
            request.logout();
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed Logout", "Unable to logout"));
            return "/login.xhtml";
        }
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Logged out successfully", "Log out successful!"));
        return "/login.xhtml";
    }

    /**
     * Get the value of password
     *
     * @return the value of password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the value of password
     *
     * @param password new value of password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Get the value of username
     *
     * @return the value of username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set the value of username
     *
     * @param username new value of username
     */
    public void setUsername(String username) {
        this.username = username;
    }

}

src/main/webapp/clerk/createEquipment.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authenticatedTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Add New Equipment
    </ui:define>

    <ui:define name="content">
         <ezcomp:equipment
            equipment="#{clerkPortalController.singleEquipment}"
            readonly="false"
            disabled="false"
            action="#{clerkPortalController.doExecuteEquipmentCreate()}"/>
    </ui:define>

</ui:composition>

src/main/webapp/clerk/createTool.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authenticatedTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Add New Tool
    </ui:define>

    <ui:define name="content">
        <ezcomp:tool
            tool="#{clerkPortalController.singleTool}"
            readonly="false"
            disabled="false"
            action="#{clerkPortalController.doExecuteToolCreate()}"/>
    </ui:define>

</ui:composition>

src/main/webapp/clerk/updateEquipment.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authenticatedTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Edit Equipment
    </ui:define>

    <ui:define name="content">
        <ezcomp:equipment
            equipment="#{clerkPortalController.singleEquipment}"
            readonly="false"
            disabled="true"
            action="#{clerkPortalController.doExecuteEquipmentUpdate()}"/>
    </ui:define>

</ui:composition>

src/main/webapp/clerk/updateMaintenance.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authenticatedTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Edit Maintenance
    </ui:define>

    <ui:define name="content">
        <ezcomp:maintenance
            maintenance="#{clerkPortalController.singleMaintenance}"
            readonly="false"
            disabled="false"
            action="#{clerkPortalController.doExecuteMaintenanceUpdate()}"/>
    </ui:define>

</ui:composition>

src/main/webapp/clerk/updateTool.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authenticatedTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Edit Tool
    </ui:define>

    <ui:define name="content">
        <ezcomp:tool
            tool="#{clerkPortalController.singleTool}"
            readonly="false"
            disabled="true"
            action="#{clerkPortalController.doExecuteToolUpdate()}"/>
    </ui:define>

</ui:composition>

src/main/webapp/clerk/viewEquipment.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authenticatedTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        View Equipment
    </ui:define>

    <ui:define name="content">
        <ezcomp:equipment
            equipment="#{clerkPortalController.singleEquipment}"
            readonly="true"
            disabled="false" />
    </ui:define>

</ui:composition>

src/main/webapp/clerk/viewMaintenance.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authenticatedTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        View Maintenance
    </ui:define>

    <ui:define name="content">
        <ezcomp:maintenance
            maintenance="#{clerkPortalController.singleMaintenance}"
            readonly="true"
            disabled="true"/>
    </ui:define>

</ui:composition>

src/main/webapp/clerk/viewTool.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authenticatedTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        View Tool
    </ui:define>

    <ui:define name="content">
        <ezcomp:tool
            tool="#{clerkPortalController.singleTool}"
            readonly="true"
            disabled="false" />
    </ui:define>

</ui:composition>

src/main/webapp/clerk/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authenticatedTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Clerk Portal
    </ui:define>

    <ui:define name="content">
        <h2 class="portal-header">Welcome #{loginController.remoteUser}<small>You can view, add and edit tools, equipment and maintenance here</small></h2>
        <section id="maintenance-info" >
            <h3 class="table-header">Maintenance Information</h3>
            <h:form class="table-header">
                <h:panelGroup class="input-group">
                    <h:inputText class="form-control" value='#{clerkPortalController.maintenanceId}'>
                        <f:passThroughAttribute name="placeholder" value="Enter maintenance id..."/>
                    </h:inputText>
                    <span class="input-group-btn">
                        <h:commandButton class="btn btn-primary" value="Search Maintenance!" action='#{clerkPortalController.doFindMaintenance(maintenanceId)}'/>
                    </span>
                </h:panelGroup>
            </h:form>
            <h:form class="table-header">
                <h:commandButton class="add btn btn-success btn-sm" action="#{clerkPortalController.doCreateMaintenance()}" value="New Maintenance Entry"/>
            </h:form>
            <h:dataTable class="table table-hover" value="#{clerkPortalController.maintenance}" var="maintenance">
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="MAINTENANCE ID" />
                    </f:facet>
                    <h:outputText value="#{maintenance.id}" />
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="EQUIPMENT ID" />
                    </f:facet>
                    <h:outputText value="#{maintenance.equipment.serialNumber}" />
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="DUE DATE" />
                    </f:facet>
                    <h:outputText value="#{maintenance.dueDate}">
                        <f:convertDateTime pattern="yyyy-MM-dd"/>
                    </h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="MAINTENANCE DONE?" />
                    </f:facet>
                    <h:outputText value="#{maintenance.maintenanceDone ? 'Yes' : 'No'}" />
                </h:column>
                <h:column>
                    <h:form>
                        <h:commandButton class="edit btn btn-default btn-xs" action="#{clerkPortalController.doUpdateMaintenance(maintenance)}" value="Edit"/>
                        <h:commandButton class="view btn btn-default btn-xs" action="#{clerkPortalController.doViewMaintenance(maintenance)}" value="View"/>
                    </h:form>
                </h:column>
            </h:dataTable>
        </section>

        <section id="equipment-info" >
            <h3 class="table-header">Equipment List</h3>
            <h:form class="table-header">
                <h:panelGroup class="input-group">
                    <h:inputText class="form-control" value='#{clerkPortalController.equipmentId}'>
                        <f:passThroughAttribute name="placeholder" value="Enter equipment serial number..."/>
                    </h:inputText>
                    <span class="input-group-btn">
                        <h:commandButton class="btn btn-primary" value="Search Equipment!" action='#{clerkPortalController.doFindEquipment(equipmentId)}'/>
                    </span>
                </h:panelGroup>
            </h:form>
            <h:form class="table-header">
                <h:commandButton class="add btn btn-success btn-sm" action="#{clerkPortalController.doCreateEquipment()}" value="New Equipment"/>
            </h:form>
            <h:dataTable class="table table-hover" value="#{clerkPortalController.equipment}" var="equipment">
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="SERIAL NUMBER" />
                    </f:facet>
                    <h:outputText value="#{equipment.serialNumber}" />
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="BRAND NAME" />
                    </f:facet>
                    <h:outputText value="#{equipment.brandName}" />
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="CATEGORY" />
                    </f:facet>
                    <h:outputText value="#{equipment.category}" />
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="TYPE" />
                    </f:facet>
                    <h:outputText value="#{equipment.type}" />
                </h:column>
                <h:column>
                    <h:form>
                        <h:commandButton class="delete btn btn-danger btn-xs" action="#{clerkPortalController.doDeleteEquipment(equipment)}" value="Delete "/>
                        <h:commandButton class="edit btn btn-default btn-xs" action="#{clerkPortalController.doUpdateEquipment(equipment)}" value="Edit"/>
                        <h:commandButton class="edit btn btn-default btn-xs" action="#{clerkPortalController.doViewEquipment(equipment)}" value="View"/>    
                    </h:form>
                </h:column>
            </h:dataTable>
        </section>

        <section id="tool-info" >
            <h3 class="table-header">Tools List</h3>
            <h:form class="table-header">
                <h:panelGroup class="input-group">
                    <h:inputText class="form-control" value='#{clerkPortalController.toolId}'>
                        <f:passThroughAttribute name="placeholder" value="Enter tool serial number..."/>
                    </h:inputText>
                    <span class="input-group-btn">
                        <h:commandButton class="btn btn-primary" value="Search Tools!" action='#{clerkPortalController.doFindTool(toolId)}'/>
                    </span>
                </h:panelGroup>
            </h:form>
            <h:form class="table-header">
                <h:commandButton class="add btn btn-success btn-sm" action="#{clerkPortalController.doCreateTool()}" value="New Tool"/>
            </h:form>
            <h:dataTable class="table table-hover" value="#{clerkPortalController.tool}" var="tool">
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="SERIAL NUMBER" />
                    </f:facet>
                    <h:outputText value="#{tool.serialNumber}" />
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="BRAND NAME" />
                    </f:facet>
                    <h:outputText value="#{tool.brandName}" />
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="CATEGORY" />
                    </f:facet>
                    <h:outputText value="#{tool.category}" />
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="TYPE" />
                    </f:facet>
                    <h:outputText value="#{tool.type}" />
                </h:column>
                <h:column>
                    <h:form>
                        <h:commandButton class="delete btn btn-danger btn-xs" action="#{clerkPortalController.doDeleteTool(tool)}" value="Delete "/>
                        <h:commandButton class="edit btn btn-default btn-xs" action="#{clerkPortalController.doUpdateTool(tool)}" value="Edit"/>
                        <h:commandButton class="edit btn btn-default btn-xs" action="#{clerkPortalController.doViewTool(tool)}" value="View"/>
                    </h:form>
                </h:column>
            </h:dataTable>
        </section>

    </ui:define>

</ui:composition>